name: privity_pos
description: "PRIVITY DRINK POS system."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  drift: 2.28.2
  drift_flutter: 0.2.7
  path_provider: ^2.1.5

  print_bluetooth_thermal: 1.2.1
  esc_pos_utils_plus: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  drift_dev: 2.28.2
  build_runner: 2.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/products/